version: '2'

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./Dashboard/Prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: grafana/grafana
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=$GF_USERS_ALLOW_SIGN_UP
      - GF_AUTH_ANONYMOUS_ENABLED=$GF_AUTH_ANONYMOUS_ENABLED
    user: "472"
    depends_on:
      - prometheus
    volumes:
      - ./Dashboard/Grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.backend=grafana"

  flask:
    build: ./api/ingest/server
    container_name: ingest_api
    restart: always
    environment:
      - APP_NAME=Ingest_Api
      - INGEST_BASE_PATH=$INGEST_BASE_PATH
      - INGEST_DEBUG=${INGEST_DEBUG:-false}
      - INGEST_PUSHGATEWAY_HOST=pushgateway
      - INGEST_PUSHGATEWAY_PORT=9091
    expose:
      - 8443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ingest.rule=Host(`ingest.localhost`)"

  reverse-proxy:
    image: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      #- "--api.insecure=true"
      - "--providers.docker"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      #- "8080:8080"
    depends_on:
      - flask
      - grafana

volumes:
  prometheus-data:
