# coding: utf-8

# flake8: noqa
"""
    CrowdSorcerer Ingest API

    The Ingest API for data ingestion into the data lake (WIP).  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: apiteam@swagger.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.api_response import ApiResponse
