FROM grafana/grafana-oss:latest

# Add plugins
# ENV GF_INSTALL_PLUGINS=plugin name

# Expose port of grafana
EXPOSE 3000

# Copy a config file from your working directory
COPY grafana.ini /etc/grafana/grafana.ini